---@diagnostic disable: undefined-global

local L = ExBoss and ExBoss.NewLocale and ExBoss:NewLocale("zhCN", true)
if not L then
    return
end

L["首页(占位)"] = true
L["首页"] = true
L["语音/配置"] = true
L["其他语音"] = true
L["副本"] = true
L["小怪CD"] = true
L["MDT"] = true
L["设置"] = true
L["副本(首领)"] = true
L["导入导出"] = true
L["时间轴"] = true
L["关闭编辑模式"] = true
L["开启编辑模式"] = true
L["更新日志"] = true
L["首页（占位）"] = true
L["BOSS技能页未就绪"] = true
L["固定时间轴预览页未就绪"] = true
L["小怪CD页未就绪"] = true
L["MDT页未就绪"] = true
L["通用设置页未就绪"] = true
L["语音包设置页异常:\n%s"] = true
L["语音包设置页未就绪"] = true
L["其他语音页异常:\n%s"] = true
L["其他语音页未就绪"] = true
L["导入导出页未就绪"] = true
L["设置页 [%s] — 待开发"] = true
L["副本 / BOSS 导航\n(待开发)"] = true
L["/exb  打开/关闭    |    /exb edit  编辑模式    |    /exb debug  调试"] = true
L["EXBoss 编辑模式"] = true
L["勾选编辑模式中要显示的项目"] = true
L["左键拖动 HUD，右键打开对应设置页"] = true
L["左键拖动 · 右键设置"] = true
L["全部显示"] = true
L["计时条"] = true
L["束状条"] = true
L["倒计时"] = true
L["中央文字"] = true
L["中央文字(中)"] = true
L["圆环进度"] = true
L["施法进度条"] = true
L["读条改名"] = true
L["改名"] = true
L["此功能为检查玩家当前读条是否能在该技能读条结束前读完"] = true
L["如果可以则显示绿色 否则显示红色 常用于比如AOE附带沉默效果的技能 用于判断当前条是否被中断"] = true
L["私人光环"] = true
L["未命名"] = true
L["首次施放时间"] = true
L["CD时间"] = true

L["男"] = true
L["女"] = true
L["小怪"] = true
L["无候选"] = true
L["...共%d个"] = true
L["  参数: level=%s sex=%s power=%s class=%s AS=%s speed=%s buff=%s"] = true
L["  观测: cast=%s channel=%s interrupted=%s active=%s success=%s"] = true
L["  校准: 无"] = true
L["  校准: npcID=%s mode=%s"] = true
L["小怪基础观测测试 - %s"] = true
L["小怪基础观测测试"] = true
L["当前不在可识别的小怪副本中。"] = true
L["当前副本没有处于战斗中的敌方姓名板。"] = true
L["  参数: 等待0.1秒采集"] = true
L["  有可能: 等待采集"] = true
L["  有可能: %s"] = true

L["MDT副本#%s"] = true
L["未选择 MDT 副本"] = true
L["未检测到 MythicDungeonTools（MDT）"] = true
L["MDT 数据库不可用"] = true
L["该副本暂无可用路线"] = true
L["路线 %s"] = true
L["模拟波次：无"] = true
L["模拟波次：%d / %d"] = true
L["测试已停止"] = true
L["未选择有效波次"] = true
L["当前副本缺少 EXBoss mapID 映射"] = true
L["未加载小怪CD Lua 数据"] = true
L["MDT 敌人数据不可用"] = true
L["当前波次没有可测试的小怪CD数据"] = true
L["测试失败：C_EncounterTimeline.AddScriptEvent 不可用"] = true
L["测试失败"] = true
L["测试中：波次 %d / %d 组怪 / %d 个技能循环"] = true
L["MDT 当前路线不可用（未选择路线）"] = true
L["当前路线"] = true
L["副本 %s"] = true
L["请选择 MDT 波次。"] = true
L["波次 %d 敌人详情"] = true
L["该波次没有怪物数据。"] = true
L["    |cff8fa0b8等级:%s|r"] = true
L["法术 %s"] = true
L["  |cff8fa0b8首次:%s|r"] = true
L["- ... 其余 %d 个已生成技能"] = true
L["- [%d] %s |cff888888(MDT原始)|r"] = true
L["- 无可用法术列表（未生成或 MDT 未提供）"] = true
L["MDT 不可用"] = true
L["请先打开 MDT 并选择路线。"] = true
L["当前副本：%s    路线：%s (%s/%s)    当前波次：%s"] = true
L["当前 MDT 路线没有波次数据。"] = true
L["波次 %d   [%d类/%d只]"] = true
L[" |cff888888(无路线)|r"] = true
L["小怪CD（MDT波次）"] = true
L["副本 -> MDT波次 -> 小怪CD预览 / 测试"] = true
L["刷新MDT"] = true
L["测关"] = true
L["测开"] = true
L["测试未开始"] = true
L["MDT波次"] = true
L["怪物 / 法术"] = true
L["MDT小窗"] = true
L["当前波次"] = true
L["当前波次怪物"] = true
L["当前波次打断怪"] = true
L["自动"] = true
L["手动"] = true
L["下一波读条怪"] = true
L["读条怪"] = true
L["无可打断怪"] = true
L["显示打断怪"] = true
L["通用设置"] = true
L["控制小窗与详情区显示哪些怪物类型。"] = true
L["控制小窗与详情区是否显示打断怪。"] = true
L["该波次没有符合设置的怪物。"] = true
L["当前波次图片：无"] = true
L["当前波次图片：%s"] = true
L["当前波次：无"] = true
L["当前波次：%d / %d"] = true
L["%.1f%%"] = true
L["0.0%%"] = true
L["当前进度：%.1f%%"] = true
L["当前进度：0.0%%"] = true
L["当前进度：%.1f / %.1f (%.1f%%)"] = true
L["当前进度：0.0 / 0.0 (0.0%%)"] = true
L["检测到玩家(或是队友) 已经开启\"林多尔米指引\"(Lindormi's Guidance)的功能,此功能会导致小怪内置CD失效/乱报\n请回到主城降钥石NPC(传送门旁边) 对话关闭"] = true
L["备注：%s"] = true
L["备注：无"] = true
L["模拟进度"] = true
L["实时进度"] = true
L["实时进度不可用"] = true
L["兵力"] = true
L["可打断读条：%s"] = true
L["备注"] = true
L["保存备注"] = true
L["MDT路线模块"] = true
L["读取 MDT 路线 / 波次，显示当前波次与下一波读条怪。"] = true
L["读取 MDT 路线 / 波次，显示当前波次打断怪。"] = true
L["模拟中"] = true
L["模拟关闭"] = true
L["小窗已开"] = true
L["小窗已关"] = true
L["模拟进度：%.1f%%"] = true
L["导入预设"] = true
L["选择预设"] = true
L["战斗中无法导入MDT路线"] = true
L["未找到可导入的MDT预设"] = true
L["MDT 导入接口不可用"] = true
L["MDT 路线解码失败"] = true
L["MDT 路线校验失败"] = true
L["MDT 路线导入失败"] = true
L["已导入MDT路线：%s - %s"] = true

L["语音包标签"] = true
L["LSM音效"] = true
L["自定义路径"] = true
L["（无标签）"] = true
L["（无LSM音效）"] = true
L["EXWIND(默认)"] = true
L["|cffff6666试听失败：语音引擎未就绪|r"] = true
L["|cff33dd88试听成功|r"] = true
L["|cffff6666试听失败：%s|r"] = true
L["请选择标签"] = true
L["请选择LSM音效"] = true
L["语音标签"] = true
L["文件路径"] = true
L["当前语音包：%s"] = true
L["监听事件：START_PLAYER_COUNTDOWN\n触发时机：剩余 5 秒\n如果玩家发起 10 秒倒数，会在开始后约 5 秒播放一次。"] = true
L["其他语音页面依赖 ExwindTools.UI，当前未就绪。请确认 ExwindCore 已正确加载后重开面板。"] = true
L["这里管理非 BOSS 时间轴类的全局语音。目前先提供“玩家倒数剩余 5 秒”播放。"] = true
L["玩家倒数 5 秒"] = true
L["使用 `START_PLAYER_COUNTDOWN`。当任意玩家发起团队倒数时，精确在剩余 5 秒播放一次你配置的语音。"] = true
L["启用玩家倒数 5 秒语音"] = true
L["语音来源"] = true
L["试听"] = true
L["点击“试听”验证当前配置。"] = true
L["行为说明"] = true
L["注意"] = true
L["1. 这是全局配置，不属于 eventID 事件表。\n2. 试听走当前页配置，实战与试听共用同一套语音解析。\n3. 若使用“语音包标签”，会读取当前已选择的全局语音包。"] = true
L["事件载荷"] = true
L["`START_PLAYER_COUNTDOWN: initiatedBy, timeRemaining, totalTime, informChat, initiatedByName`\n运行时按 `timeRemaining` 计算目标时间，因此 10 秒倒数会在剩余 5 秒准点播放，不会在发起瞬间提前响。"] = true
L["每个数字都可以在“语音包标签”和“LSM音效”之间切换；Boss/小怪技能的提前秒数仍然在各自设置页里配置。"] = true
L["语音包选择统一走“语音/配置”页；倒数是否实际播放仍然跟随具体法术设置，这里只控制数字 1-5 的启用、来源和 LSM 选择。"] = true
L["数字开关与试听"] = true
L["数字 %d"] = true
L["来源"] = true
L["语音包"] = true
L["私人光环监控"] = true
L["启用私人光环监控"] = true
L["进入编辑模式"] = true
L["图标外观"] = true
L["图标大小"] = true
L["图标间距"] = true
L["排列方向"] = true
L["显示边框"] = true
L["边框缩放"] = true
L["倒计时"] = true
L["显示冷却圈"] = true
L["显示数字倒计时"] = true
L["位置"] = true
L["水平位置 (X)"] = true
L["垂直位置 (Y)"] = true
L["锚点"] = true
L["屏幕中央"] = true
L["左上角"] = true
L["上方中央"] = true
L["右上角"] = true
L["左侧中央"] = true
L["右侧中央"] = true
L["左下角"] = true
L["下方中央"] = true
L["右下角"] = true
L["重置位置"] = true
L["--[[ Function ]]"] = true
L["BOSS施法联动"] = true
L["BOSS施法时显示圆环"] = true
L["BOSS施法时显示读条"] = true
L["施法进度条设置"] = true
L["读条设置"] = true
L["显示引导"] = true
L["与中央圆环使用相同触发逻辑，额外显示一根施法/引导进度条。"] = true
L["圆环进度设置"] = true
L["屏幕中央显示圆环进度"] = true
L["功能"] = true
L["启用"] = true
L["施法填充方式"] = true
L["引导填充方式"] = true
L["顺时针填满"] = true
L["顺时针消退"] = true
L["逆时针填满"] = true
L["逆时针消退"] = true
L["圆环样式"] = true
L["细环 1"] = true
L["细环 2"] = true
L["标准环"] = true
L["圆环尺寸"] = true
L["颜色"] = true
L["透明度"] = true
L["测试圆环(3秒)"] = true
L["测试施法(3秒)"] = true
L["测试引导(3秒)"] = true
L["暴雪时间轴模式启用5秒倒数"] = true
L["只能整体启用或禁用，无法按事件过滤。"] = true
L["批量修改"] = true
L["批量启用/禁用事件功能，并真实写入 override。"] = true
L["这里用于真实批量启用/禁用事件功能。第一版先覆盖普通事件的常用开关，并直接写入 override。"] = true
L["选择作用的BOSS"] = true
L["选择哪些事件"] = true
L["选择要做什么改动"] = true
L["选择禁用启用"] = true
L["作用范围"] = true
L["当前战斗BOSS"] = true
L["当前战斗副本全部BOSS"] = true
L["全部大秘境BOSS"] = true
L["全部团本BOSS"] = true
L["全部BOSS"] = true
L["目标筛选"] = true
L["全部事件"] = true
L["仅当前已启用"] = true
L["仅当前已禁用"] = true
L["批量动作"] = true
L["动作 1"] = true
L["动作 2"] = true
L["动作 3"] = true
L["全部小怪法术"] = true
L["全部私人光环"] = true
L["私人光环分类"] = true
L["全部分类"] = true
L["分类1"] = true
L["分类2"] = true
L["分类3"] = true
L["匹配文本"] = true
L["匹配语音"] = true
L["替换为"] = true
L["替换来源"] = true
L["把什么内容"] = true
L["变更为"] = true
L["当前范围无可替换文本"] = true
L["当前范围无可替换语音"] = true
L["当前无可用语音标签"] = true
L["批量替换"] = true
L["倒数文本替换"] = true
L["中央文本替换"] = true
L["计时条改名替换"] = true
L["中央警告语音替换"] = true
L["施法开始语音替换"] = true
L["提前5秒语音替换"] = true
L["[启用/禁用] 启用"] = true
L["[启用/禁用] 中央文本"] = true
L["[启用/禁用] 提前5秒"] = true
L["[启用/禁用] 计时条改名"] = true
L["[启用/禁用] 中央警告语音"] = true
L["[启用/禁用] 施法开始语音"] = true
L["[启用/禁用] 提前5秒语音"] = true
L["[启用/禁用] BOSS施法时显示圆环"] = true
L["[启用/禁用] 颜色覆盖"] = true
L["[文本替换] 倒数文本"] = true
L["[文本替换] 中央文本"] = true
L["[文本替换] 计时条改名"] = true
L["[语音替换] 中央警告语音"] = true
L["[语音替换] 施法开始语音"] = true
L["[语音替换] 提前5秒语音"] = true
L["[语音替换] 私人光环语音"] = true
L["私人光环语音替换"] = true
L["当批量动作选择“倒数文本替换”时，会按当前生效配置的倒数文本匹配，再写入当前 author override。"] = true
L["当批量动作选择“中央文本替换”时，会按当前生效配置的中央文本匹配，再写入当前 author override。"] = true
L["当批量动作选择“计时条改名替换”时，会按当前生效配置的计时条改名匹配，再写入当前 author override。"] = true
L["当批量动作选择“中央警告语音替换”时，会按当前生效配置的语音匹配，再写入当前 author override。"] = true
L["当批量动作选择“施法开始语音替换”时，会按当前生效配置的语音匹配，再写入当前 author override。"] = true
L["当批量动作选择“提前5秒语音替换”时，会按当前生效配置的语音匹配，再写入当前 author override。"] = true
L["当批量动作选择替换类动作时，会按当前生效配置匹配，再写入当前 author override。"] = true
L["操作"] = true
L["禁用"] = true
L["恢复默认"] = true
L["未选择"] = true
L["束状条显示"] = true
L["计时条显示"] = true
L["屏幕提示"] = true
L["中央警告语音"] = true
L["施法开始语音"] = true
L["提前5秒"] = true
L["提前5秒语音"] = true
L["颜色覆盖"] = true
L["计时文字染色"] = true
L["生成预览"] = true
L["确认应用"] = true
L["这是物理修改，不是额外叠一层运行时规则。应用后会真实写入事件 override，并在必要时重启当前 encounter。"] = true
L["副本首领时间轴、语音提示、团队框架发光与配置方案。"] = true
L["插件作者: EXWIND"] = true
L["如果你觉得插件不错，可以小额赞助。"] = true
L["赞助链接"] = true
L["问题反馈"] = true
L["遇到问题、语音不合适、配置建议都可以反馈。"] = true
L["也可以在 Bilibili @绿色歹人 直播间直接询问。"] = true
L["制作名单"] = true
L["感谢参与插件制作、翻译、语音与测试的朋友。"] = true
L["插件作者"] = true
L["开发协助"] = true
L["团本语音制定"] = true
L["其他协助"] = true
L["本地化翻译"] = true
L["英语, 西班牙语"] = true
L["版权说明"] = true
L["语音包版权归语音包作者所有。每位作者方案不同，如需单独使用请咨询语音包作者。"] = true
L["插件本体（不含 Lib）版权：CC BY-NC-ND 4.0"] = true
L["语音包"] = true
L["排名不分先后，AI 随机排序，将定期重新排序。"] = true
L["感谢使用 EXBoss。"] = true
L["反馈请尽量附上副本、首领、难度、职业职责、错误截图或复现步骤。"] = true
L["自动跟随客户端"] = true
L["强制 zhCN"] = true
L["强制 enUS"] = true
L["这是非英文语音包。\n确认后将停止英文环境下的自动强制切换。"] = true
L["自动对话"] = true
L["启用自动对话"] = true
L["[大秘境] 自动对话学院(AA)BUFF"] = true
L["[大秘境] 自动对话洞窟(MC)大锅BUFF"] = true
L["[大秘境] 自动对话萨隆矿坑救人(POS)"] = true
L["仅自动选择普通对话选项，不会自动接任务。"] = true
L["界面语言"] = true
L["缩放"] = true
L["立即重载界面"] = true
L["当前设置：%s | 客户端：%s | 当前生效：%s\n仅影响 EXBoss 自身本地化文本，切换后建议重载界面。"] = true
L["当前预览"] = true
L["请先选择范围与动作，然后点击生成预览。"] = true
L["命中事件数量"] = true
L["动作数量"] = true
L["已应用批量修改。"] = true
L["请至少选择一条批量动作。"] = true
L["切换成功：%s\n是否现在重载界面以完整生效？"] = true
L["当前槽位"] = true
L["导出"] = true
L["导入"] = true
L["关闭"] = true
L["重命名"] = true
L["未命名配置"] = true
L["无"] = true
L["导出内容"] = true
L["导入内容"] = true
L["配置名称"] = true
L["备注（可选）"] = true
L["设置页全部设置"] = true
L["导入设置页全部设置（立即应用）"] = true
L["导入作者名（留空则使用配置名）"] = true
L["外观设置（计时条外观等）"] = true
L["导入外观设置（立即应用）"] = true
L["粘贴导出字符串"] = true
L["解析"] = true
L["执行导入"] = true
L["槽位概览"] = true
L["选择方案"] = true
L["此区域展示所有已导入的作者方案；重命名/删除会作用到整套作者方案。"] = true
L["确认删除方案：%s ？"] = true
L["导入导出模块未加载"] = true
L["请至少勾选一项导出内容"] = true
L["导出失败："] = true
L["导出成功"] = true
L["请先粘贴导出字符串"] = true
L["解析失败："] = true
L["读取摘要失败："] = true
L["配置名："] = true
L["导出者："] = true
L["时间："] = true
L["备注："] = true
L["外观："] = true
L["大米配置："] = true
L["团本配置："] = true
L["包含"] = true
L[" (%d 条事件)"] = true
L["："] = true
L["解析成功，选择要导入的内容后点击[执行导入]"] = true
L["请先点击[解析]按钮"] = true
L["请至少勾选一项导入内容"] = true
L["导入失败："] = true
L["导入成功："] = true
L["作者方案：%s    槽位：%s"] = true
L["请选择要重命名的方案。"] = true
L["请输入新的方案名称。"] = true
L["已重命名："] = true
L["重命名失败："] = true
L["请选择要删除的方案。"] = true
L["已删除："] = true
L["删除失败："] = true
L["复制并自动关闭，或点击"] = true
L["按钮"] = true
L["已复制到剪贴板"] = true
L["计时条设置"] = true
L["计时条所有外观的设置"] = true
L["条增长方式"] = true
L["左到右填充"] = true
L["左到右消退"] = true
L["右到左填充"] = true
L["右到左消退"] = true
L["左到右填满"] = true
L["右到左填满"] = true
L["计时条外观"] = true
L["外部(左侧)"] = true
L["文字前"] = true
L["文字后"] = true
L["新组件"] = true
L["束状条设置"] = true
L["背景设置"] = true
L["轨道宽度"] = true
L["轨道高度"] = true
L["显示图标"] = true
L["移动方向"] = true
L["背景线粗细"] = true
L["背景线颜色"] = true
L["5秒线粗细"] = true
L["5秒线颜色"] = true
L["名称位置"] = true
L["图标左边"] = true
L["图标右边"] = true
L["背景材质"] = true
L["背景颜色"] = true
L["边框材质"] = true
L["边框颜色"] = true
L["边框粗细"] = true
L["边框外扩"] = true
L["边框"] = true
L["图标设置"] = true
L["图标ID (可选)"] = true
L["倒数反转"] = true
L["宽度 (Width)"] = true
L["高度 (Height)"] = true
L["图标边框设置"] = true
L["启用图标边框"] = true
L["图标边框材质"] = true
L["图标边框颜色"] = true
L["图标边框粗细"] = true
L["图标边框间距 (Padding)"] = true
L["边框内距"] = true
L["图标左"] = true
L["图标右"] = true
L["文字左"] = true
L["文字右"] = true
L["宽度"] = true
L["高度"] = true
L["倒计时设置"] = true
L["技能预警时在屏幕中央显示5秒倒数文字。\n|cff00ff00%s|r = 技能名称  |cffffd100%t|r = 倒计时数字"] = true
L["显示小数点"] = true
L["最大条数"] = true
L["上下间距"] = true
L["提示文字模板"] = true
L["模板（|cff00ff00%s|r=技能名  |cffffd100%t|r=倒计时数字）"] = true
L["提示文字字体（%s）"] = true
L["提示文字"] = true
L["倒计时数字字体（%t）"] = true
L["倒计时数字"] = true
L["场景预览"] = true
L["切换编辑模式预览"] = true
L["测试倒计时"] = true
L["|cffaaaaff预览：|r\n%s"] = true
L["坦克尖刺"] = true
L["技能触发时在屏幕中央显示技能名称（淡入 → 停留 → 淡出）。"] = true
L["持续时间(秒)"] = true
L["中央文字公告(中)"] = true
L["中字提示测试文字"] = true
L["向上"] = true
L["向下"] = true
L["通用"] = true
L["显示背景"] = true
L["显示边框"] = true
L["排列"] = true
L["大小"] = true
L["X偏移"] = true
L["Y偏移"] = true
L["图案倒数时间"] = true
L["副本 "] = true
L["首领 "] = true
L["事件 "] = true
L["规则编辑"] = true
L["条件命名"] = true
L["事件ID"] = true
L["剩余时间"] = true
L["只对 fixed / fixed_ai 生效。文本可用 {name}、{eventID}、{spellID}。"] = true
L["动作设置"] = true
L["动作"] = true
L["文本内容"] = true
L["音效设置"] = true
L["音效来源"] = true
L["条件 %02d"] = true
L["停用"] = true
L["暂无规则"] = true
L["条件系统（固定轴/AI轴）"] = true
L["规则创建时按 eventID 绑定到 fixed/fixed_ai 计时器；运行时只检查计时器自身条件，不扫描全表。"] = true
L["启用条件系统"] = true
L["选择规则"] = true
L["新增规则"] = true
L["|cff33ee77已新增规则|r"] = true
L["复制规则"] = true
L["|cff33ee77已复制规则|r"] = true
L["删除规则"] = true
L["|cffff8888已删除规则|r"] = true
L["当前没有规则。点击“新增规则”后开始编辑。"] = true
L["技能"] = true
L["未命名技能"] = true
L["未知副本 "] = true
L["未知副本"] = true
L["固定时间轴预览"] = true
L["请选择左侧首领查看 3 分钟时间轴。"] = true
L["%s  |  技能:%d  |  3分钟节点:%d"] = true
L["%d 次"] = true
L["首轮>3:00"] = true
L["固定轴首领: %d  |  技能总数: %d  |  窗口: %s"] = true
L["encounter:%d  |  技能:%d  |  节点:%d"] = true
L["固定时间轴总览"] = true
L["按首领查看固定轴技能在前 3 分钟内的出现节点，便于快速校对时间轴节奏。"] = true
L["固定轴首领: 0"] = true
L["暂无固定时间轴数据"] = true
L["暂无时间轴节点"] = true
L["这里统一管理 EXBoss 的全局显示模式与语音输出"] = true
L["时间轴启用方案"] = true
L["载入设置"] = true
L["法术名称显示次数"] = true
L["音频输出选项"] = true
L["团本配置尚未完工，确认启用？"] = true
L["通用颜色方案"] = true
L["Boss 技能页会直接读取这里的配色方案。现在这页也走 Grid，可拖拽布局；颜色编辑走按钮打开取色器。"] = true
L["固定方案"] = true
L["编辑颜色"] = true
L["方案名称"] = true
L["名称"] = true
L["技能名称测试文字"] = true
L["条件系统"] = true
L["私人光环监控"] = true
L["计时条"] = true
L["束状条"] = true
L["[文本]5秒倒数"] = true
L["[文本]文字公告(大)"] = true
L["[文本]文字公告(中)"] = true
L["中央圆环"] = true
L["团队框架发光"] = true
L["小怪CD"] = true
L["副本额外功能"] = true
L["语音注册监控"] = true
L["重置设置"] = true
L["显示"] = true
L["小怪"] = true
L["其他"] = true
L["固定轴/AI轴 IF/THEN 条件触发规则。"] = true
L["监控玩家自身的3个私人光环槽位，支持图标大小、位置、倒计时、音效等配置。"] = true
L["中央倒数文字与字体、位置。"] = true
L["中央文字公告样式与位置。"] = true
L["中等尺寸中央提示，供血量转阶段、易伤、站位等功能模块复用。"] = true
L["屏幕中央圆环进度样式、大小、位置。"] = true
L["通用队伍/团队框架发光样式与预览。"] = true
L["小怪内置CD的全局计时条规则。"] = true
L["特定副本/首领的额外辅助模块。"] = true
L["查看当前语音注册细节（默认仅显示非团本）：副本 > BOSS名称(数量) + eventID(trigger0/1/2)。"] = true
L["提供四种重置方式：\n1) 仅重置外观设置\n2) 仅重置小怪内置CD设置\n3) 重置所有配置（不包含外观）\n4) 清除全部设置（包含外观）"] = true
L["12.0大秘境"] = true
L["12.0团本"] = true
L["其他"] = true
L["延迟"] = true
L["提前"] = true
L["中央警告"] = true
L["施法开始"] = true
L["固定时间轴"] = true
L["暴雪轴"] = true
L["事件 "] = true
L["未知事件"] = true
L["首领 "] = true
L["未知首领"] = true
L["首领列表"] = true
L["副本 "] = true
L["未知副本 "] = true
L["副本切换"] = true
L["法术选择"] = true
L["当前法术设置"] = true
L["点击左侧法术后，可在此查看法术描述。"] = true
L["法术 "] = true
L["私"] = true
L["暂无描述。"] = true
L["暂无施法信息"] = true
L["未启用"] = true
L["启用颜色覆盖"] = true
L["自定义颜色"] = true
L["文本设置"] = true
L["显示设置"] = true
L["计时规则"] = true
L["姓名版设置"] = true
L["说明"] = true
L["中央文本"] = true
L["提前(秒)"] = true
L["中央文本内容（可用 {name}）"] = true
L["中央文本内容"] = true
L["(可用 {name})"] = true
L["计时条改名"] = true
L["语音设置"] = true
L["显示位置"] = true
L["竖条"] = true
L["坦克"] = true
L["治疗"] = true
L["输出"] = true
L["秒"] = true
L["施法检测"] = true
L["未选择法术"] = true
L["点击上方法术卡片后，可在此查看法术描述。"] = true
L["点击上方法术卡片后，可在此配置单法术提醒选项。"] = true
L["无动态头像"] = true
L["加载中"] = true
L["该分类无副本数据"] = true
L["当前副本暂无 BOSS 数据"] = true
L["轴模式"] = true
L["测试首领"] = true
L["请选择有技能数据的 BOSS"] = true
L["未知技能 "] = true
L["已禁用"] = true
L["未选择副本"] = true
L["技能数"] = true
L["轴"] = true
L["生效"] = true
L["无"] = true
L["未知来源"] = true
L["私人光环"] = true
L["私人光环法术"] = true
L["来源"] = true
L["来源NPCID"] = true
L["归属"] = true
L["ExwindGrid 不可用，无法渲染私人光环设置。"] = true
L["未知法术"] = true
L["ExwindGrid 不可用，无法渲染设置区。"] = true
L["技能 "] = true
L["ExBoss 官方默认语音包"] = true
L["覆盖常见首领与大秘境语音标签，标准参考实现。"] = true
L["暂无描述"] = true
L["—"] = true
L["标签目录未加载"] = true
L["团本坦克"] = true
L["团本DPS"] = true
L["团本治疗"] = true
L["大米坦克"] = true
L["大米DPS"] = true
L["大米治疗"] = true
L["Boss 配置模块未加载"] = true
L["当前职责：%s"] = true
L["6 槽位作者方案已接入，副本页会按当前职责自动写入对应方案。"] = true
L["已切换 "] = true
L["应用失败："] = true
L["请选择配置"] = true
L["%d 标签"] = true
L["● 当前使用中"] = true
L["缺少语音：?"] = true
L["缺少语音：%d"] = true
L["缺少语音：0"] = true
L["缺少语音"] = true
L["、"] = true
L["已覆盖默认语音标签"] = true
L["语音 / 配置"] = true
L["左侧选择语音包，右侧按团本 / 大米配置作者方案。"] = true
L["选择语音包"] = true
L["当前语音包"] = true
L["简介"] = true
L["作者"] = true
L["版本"] = true
L["配置方案"] = true
L["按 6 个职责槽位选择作者方案；副本页会按当前职责自动写入对应的团本 / 大米方案。"] = true
L["当前职责进入团本时自动使用。"] = true
L["当前职责进入大米时自动使用。"] = true
L[" 方案"] = true
L["团本方案"] = true
L["大米方案"] = true
L["提示：当前是什么职责，就自动使用并编辑对应的团本/大米方案。"] = true
L["请选择..."] = true
L["全局显示模式与语音输出。"] = true
L["4个固定颜色方案 + 1个自定义方案 + 最多3个额外方案。Boss技能页可直接选择方案或自定义颜色。"] = true
L["监控玩家自身的3个私人光环槽位，支持图标大小、位置、倒计时、音效等配置。"] = true
L["计时条外观、文字、位置。"] = true
L["束状条外观、轨道、位置。"] = true
L["中央倒数文字与字体、位置。"] = true
L["中央文字公告样式与位置。"] = true
L["中等尺寸中央提示，供血量转阶段、易伤、站位等功能模块复用。"] = true
L["屏幕中央圆环进度样式、大小、位置。"] = true
L["通用队伍/团队框架发光样式与预览。"] = true
L["小怪内置CD的全局计时条规则。"] = true
L["特定副本/首领的额外辅助模块。"] = true
L["查看当前语音注册细节（默认仅显示非团本）：副本 > BOSS名称(数量) + eventID(trigger0/1/2)。"] = true
L["提供四种重置方式：\n1) 仅重置外观设置\n2) 仅重置小怪内置CD设置\n3) 重置所有配置（不包含外观）\n4) 清除全部设置（包含外观）"] = true
L["通用"] = true
L["显示"] = true
L["仅束状条"] = true
L["两者都启用"] = true
L["仅计时条"] = true
L["两者都隐藏"] = true
L["向右增长"] = true
L["向左增长"] = true
L["坦克方案"] = true
L["治疗方案"] = true
L["减伤方案"] = true
L["机制方案"] = true
L["PartyFrameGlow 模块未加载。"] = true
L["预览中："] = true
L["预览已结束。"] = true
L["发光已关闭，启用后再预览。"] = true
L["没有找到可发光的队伍/团队框架。请确认框架已显示。"] = true
L["可用上方按钮测试当前样式。"] = true
L["姓名版图标预览"] = true
L["姓名版锚点"] = true
L["全局条显示模式"] = true
L["控制全局显示：仅计时条 / 仅束状条 / 两者都启用 / 两者都隐藏。\n可单独关闭大秘境或团本首领提示；关闭后将整体禁用该场景的 Boss 计时、中央文字、语音与颜色覆盖。\n可选：首领战中自动将战斗音频预警分类音量静音（0），脱战恢复原值。"] = true
L["全局语音输出"] = true
L["当前语音注册状态"] = true
L["已注册BOSS: 0  |  已注册事件: 0"] = true
L["最近刷新: -"] = true
L["刷新"] = true
L["暂无已注册BOSS"] = true
L["Boss技能页面可选择下列方案；选择“自定义颜色”时使用“自定义方案”。勾选启用的额外方案会出现在技能页下拉。"] = true
L["额外方案（最多3个）"] = true
L["推荐先使用针对性重置：外观问题用“仅重置外观设置”，小怪CD异常用“重置小怪内置CD设置”。\n“重置所有配置（不包含外观）”会清空通用设置、语音配置、技能配置与时间轴设置，但保留外观。\n“清除全部设置”会把 EXBoss 的全部配置都恢复到初始状态。"] = true
L["仅重置外观设置"] = true
L["重置小怪内置CD设置"] = true
L["重置所有配置（不包含外观）"] = true
L["清除全部设置（包含外观）"] = true
L["小怪CD全局设置"] = true
L["隐藏 X 秒以上的计时条：只在最后 X 秒显示小怪计时条。\n技能冷却结束后 X 秒隐藏：条子到点后若怪物尚未成功施法，会停在 0 继续保留；成功施法后才进入下一轮 CD，或超过额外 X 秒后隐藏。\n隐藏NPCID只隐藏姓名版上方的识别文字，不影响内置CD图标。\n姓名版图标参数控制图标本体；姓名版倒数字体参数控制图标上的数字大小、颜色、字体、描边和偏移。"] = true
L["这里配置通用队伍/团队框架发光样式。它只负责框架发光本身，具体机制模块是否使用这套默认样式由模块调用时决定。"] = true
L["EXUI:CreateGlowSettings 不可用，无法渲染发光参数。"] = true
L["预览自己"] = true
L["预览当前队伍"] = true
L["停止预览"] = true
L["预览已停止。"] = true
L["查找顺序：PlayerFrame、PartyFrame、CompactPartyFrame、CompactRaidFrame，再递归扫描 UIParent。第三方队伍框架如果没有标准 unit 属性，可能需要单独适配。"] = true
L["执政团之座 2号 - 狗跳点名"] = true
L["实战只在 encounterID=2066 且事件237附近扫描队友有害光环实例ID，用最近两次目标排除下次候选。预览会显示样例面板并让候选队友框架发光，不写入实战记录。"] = true
L["中文配音语音包"] = true
L["忘忧景久语音包，标签与默认包兼容，可直接替换全局语音。"] = true
L["顾衣衿少女音版本，保留同一套标签结构，便于统一切换。"] = true
L["顾衣衿御姐音版本，保持标签兼容，适配现有副本方案。"] = true
L["Kele 语音包，标签兼容默认方案，可直接用于副本配置。"] = true
L["夏一可语音包，保持标准标签兼容，可直接切换使用。"] = true
L["然然语音包，包含标准标签与倒数语音。"] = true
L["糖糖酱语音包，标签结构与默认包兼容。"] = true
L["小羊 Yagi 语音包，包含标准标签与倒数语音。"] = true
L["你好牛语音包，来源目录为牛师傅，包含标准标签与倒数语音。"] = true
L["绫零语音包，使用标准标签结构，兼容默认包配置。"] = true
L["露露緹婭语音包，标签结构与默认包兼容。"] = true
L["隐藏"] = true
L["秒以上的计时条"] = true
L["技能冷却结束后"] = true
L["秒隐藏"] = true
L["隐藏NPCID"] = true
L["姓名版图标方向"] = true
L["姓名版图标参数"] = true
L["姓名版倒数字体参数"] = true
L["默认发光样式"] = true
L["默认持续时间"] = true
L["%.1f 秒"] = true
L["显示模式"] = true
L["启用大秘境首领提示"] = true
L["启用团本首领提示"] = true
L["首领战时自动关闭战斗音频预警"] = true
L["开启中央文字预警提示音（预设叮一声）"] = true
L["开启中央文字预警（注意：如果关闭会导致语音不工作）"] = true
L["关闭暴雪原生计时条"] = true
L["输出通道"] = true
L["全局音量"] = true
L["语音引擎未就绪，无法读取注册状态。"] = true
L["无数据"] = true
L["注册快照为空。"] = true
L["  |  未匹配BOSS事件: %d"] = true
L["  |  团本已过滤: %d"] = true
L["非团本已注册BOSS: %d  |  非团本事件: %d / 全量: %d  |  触发器事件(0/1/2): %d/%d/%d%s"] = true
L["未知"] = true
L["（预估）"] = true
L["（实测）"] = true
L["  |  最近错误: "] = true
L["  |  作用域: %s[InstanceID:%d]"] = true
L["最近刷新: "] = true
L["暂无非团本已注册BOSS"] = true
L["仅重置计时条/束状条/倒计时/文字公告的外观样式，不删除法术配置。是否继续？"] = true
L["确定"] = true
L["取消"] = true
L["|cffffcc00将清空小怪内置CD的全局设置、姓名版设置和所有法术覆盖。|r\n会重新使用 Lua 预设默认值。是否继续？"] = true
L["确定重置"] = true
L["|cffffcc00将清空 EXBoss 的通用设置、语音配置、技能配置与时间轴设置，但保留外观样式。|r\n确认继续？"] = true
L["|cffff4444危险：将清空 EXBoss 的全部设置（包含外观）并重载。此操作不可撤销。|r\n确认继续？"] = true
L["确定清空"] = true
L["自定义方案"] = true
L["额外方案"] = true
L["设置页"] = true
L[" 未就绪"] = true
L["条目 "] = true
L["自定义方案名"] = true
L["自定义方案颜色"] = true
L["启用狗跳点名模块"] = true
L["预览狗跳点名面板"] = true
L["本次动作"] = true
L["当前范围没有命中任何事件。"] = true
L["预览前20条事件"] = true
L["其余省略，共%d条。"] = true
L["本次动作"] = true
L["当前范围没有命中任何事件。"] = true
L["预览前20条事件"] = true
L["其余省略，共%d条。"] = true
L["已应用批量修改。"] = true
L["请至少选择一条批量动作。"] = true
L["DPS职责下不提示坦克技能"] = true
L["治疗职责下不提示坦克技能"] = true
L["小怪CD设置"] = true
L["导入小怪CD设置（全量覆盖）"] = true
L["小怪CD设置："] = true
L["控制全局显示：仅计时条 / 仅束状条 / 两者都启用 / 两者都隐藏。\n可单独关闭大秘境或团本首领提示；关闭后将整体禁用该场景的 Boss 计时、中央文字、语音与颜色覆盖。\n可按当前职责过滤坦克类 Boss 技能提示。\n可选：首领战中自动将战斗音频预警分类音量静音（0），脱战恢复原值。"] = true
L["该 Boss 无固定时间轴技能数据"] = true
L["选择 Boss"] = true
L["技能显示设置"] = true
L["勾选控制每条技能是否在束状条/计时条/屏幕显示，预警秒数可单独调整。留空=使用技能默认值。"] = true
L["技能名称"] = true
L["屏幕警告"] = true
L["预警(秒)"] = true
L["encounterID:%s  共%d个私人光环法术"] = true
L["共%d个私人光环法术"] = true
L["团本首领战  |  encounterID:%s  |  法术数:%d"] = true
L["大秘境副本  |  法术数:%d  |  BOSS组:%d  |  小怪法术:%d"] = true
L["【%s】"] = true
L["准备易伤"] = true
L["准备易伤阶段"] = true
L["易伤阶段"] = true
L["易伤结束"] = true
L["易伤阶段结束"] = true
L["%s易伤阶段"] = true
L["易伤阶段(%s)"] = true
L["转阶段"] = true
L["转阶段 {lead}%"] = true
L["阶段转换"] = true
L["倒数语音"] = true
L["技能数字倒数语音、名称提前秒数与单数字试听。"] = true
L["启用倒数"] = true
L["倒数文本"] = true
L["提前倒数"] = true
L["播放文字"] = true
L["作者临时禁用语音"] = true
L["该技能语音已被作者临时禁用"] = true

-- auto-added by sync_locale_keys.py
L["进入战斗提示"] = true
L["离开战斗提示"] = true
L["全选"] = true
L["水平偏移 (X)"] = true
L["垂直偏移 (Y)"] = true
L["TTS语音"] = true
L["TTS文本"] = true
L["语音分类"] = true
L["未知首领 "] = true
L["显示名称"] = true
L["显示时间"] = true
L["法术名称"] = true
L["提示图标"] = true
L["显示提示图标"] = true
L["提示图标锚点"] = true
L["左右排列"] = true
L["上下排列"] = true
L["增长方向"] = true
L["测试施法检测"] = true
L["时间文本"] = true
L["倒数文字"] = true
L["播放音效"] = true
L["开启暴雪中央文字预警（注意：如果关闭会导致语音不工作）"] = true
L["与中央圆环同源的施法/引导进度条。"] = true
L["背景"] = true
L["低"] = true
L["中"] = true
L["高"] = true
L["对话"] = true
L["全屏"] = true
L["全屏对话"] = true
L["提示"] = true
L["姓名版图标层级"] = true
L["特别协助"] = true
L["感谢在开发验证与实战反馈中提供直接协助的朋友。"] = true
L["英文本地化翻译与翻译插件协助。"] = true
L["英文本地化翻译"] = true
L["本地化翻译插件协助"] = true
L["全选复制"] = true
L["删除"] = true
L["请先勾选一个Boss槽位"] = true
L["作者Lua导出一次只能勾选一个Boss槽位"] = true
L["预设插件片段已生成"] = true
L["导出预设插件片段"] = true
L["把内容粘贴到模板插件的 Config/PresetPayload.lua 后即可打包。"] = true
L["作者Lua导出不包含设置页外观"] = true
L["作者Lua导出不包含小怪CD"] = true
L["内置作者Lua已生成"] = true
L["导出内置作者Lua"] = true
L["把内容直接粘贴到对应作者文件："] = true
L["作者插件Lua不包含设置页外观"] = true
L["作者插件Lua不包含小怪CD"] = true
L["作者插件Lua已生成"] = true
L["导出作者插件Lua"] = true
L["把内容直接粘贴到模板插件槽位文件："] = true
L["设置页配置："] = true
L["导出字符串"] = true
L["预设插件片段"] = true
L["内置作者Lua"] = true
L["作者插件Lua"] = true
L["当前进度：未获取"] = true
L["路线套装"] = true
L["导入MDT"] = true
L["请选择左侧一个私人光环对象"] = true
L["团本首领：%d  |  大米副本：%d"] = true
L["对象列表"] = true
L["当前对象没有私人光环法术。"] = true
L["重置"] = true
L["间距"] = true
L["最大显示数量"] = true
L["语音/配置页面依赖 ExwindTools.UI，当前未就绪。请确认 ExwindCore 已正确加载后重开面板。"] = true
L["已切换路线套装：%s"] = true
L["已选择路线套装：%s（尚未导入）"] = true
L["已导入MDT路线：%s"] = true
L["通道"] = true
L["中央中号"] = true
L["中央大字"] = true
L["圆环"] = true
L["图标"] = true
L["未填写，触发时使用逻辑层传入文案"] = true
L["预计目标角色：治疗 / 输出"] = true
L["中央文字：%s"] = true
L["开启"] = true
L["中央文字覆盖：%s"] = true
L["施法开始语音：%s"] = true
L["圆环：%s"] = true
L["计时条：%s"] = true
L["图标：%s"] = true
L["这一版只是原型页，用来确认布局、字段和交互方向。"] = true
L["法术列表"] = true
L["原型阶段先放 1 个法术，后续扩到 15-20 个。"] = true
L["点击左侧法术后，可在此查看详情。"] = true
L["姓名版"] = true
L["读条"] = true
L["触发类型"] = true
L["自定义事件"] = true
L["事件分类"] = true
L["自定义小怪事件"] = true
L["自定义小怪事件。"] = true
